import * as Gardens from "./gardens";
import * as Strategic from "./strategic";
import { PIECES } from "@/constants";

export const INITIAL_ARMY = [
  { type: PIECES.KING, count: 1 },
  { type: PIECES.QUEEN, count: 1 },
  { type: PIECES.ROOK, count: 2 },
  { type: PIECES.BISHOP, count: 2 },
  { type: PIECES.KNIGHT, count: 2 },
  { type: PIECES.PAWN, count: 8 },
];

export const DEFAULT_SEEDS = [
  // Garden Layouts (Nature + Scenarios)
  {
    id: "default-divide",
    name: "The Great Divide",
    seed: Gardens.createGreatDivide(),
    mode: "2p-ew",
    createdAt: new Date().toISOString(),
  },
  {
    id: "default-sherwood",
    name: "Sherwood Forest",
    seed: Gardens.createSherwood(),
    mode: "2p-ns",
    createdAt: new Date().toISOString(),
  },
  {
    id: "default-oasis",
    name: "Oasis",
    seed: Gardens.createOasis(),
    mode: "2p-ns",
    createdAt: new Date().toISOString(),
  },
  {
    id: "default-swamp",
    name: "Swamp Fever",
    seed: Gardens.createSwampFever(),
    mode: "2p-ns",
    createdAt: new Date().toISOString(),
  },
  {
    id: "default-islands",
    name: "Island Hopping",
    seed: Gardens.createIslandHopping(),
    mode: "2p-ns",
    createdAt: new Date().toISOString(),
  },
  {
    id: "default-snake",
    name: "Snake River",
    seed: Gardens.createSnakeRiver(),
    mode: "2p-ns",
    createdAt: new Date().toISOString(),
  },
  {
    id: "default-trails",
    name: "Forest Trails",
    seed: Gardens.createForestTrails(),
    mode: "2p-ns",
    createdAt: new Date().toISOString(),
  },
  {
    id: "default-archipelago",
    name: "Archipelago",
    seed: Gardens.createArchipelago(),
    mode: "2p-ns",
    createdAt: new Date().toISOString(),
  },
  {
    id: "default-mirage",
    name: "Mirage Lake",
    seed: Gardens.createMirageLake(),
    mode: "2p-ns",
    createdAt: new Date().toISOString(),
  },

  // Scenario Gardens
  {
    id: "default-fvs",
    name: "Forest vs Swamp",
    seed: Gardens.createForestVsSwamp(),
    mode: "2p-ns",
    createdAt: new Date().toISOString(),
  },
  {
    id: "default-mvr",
    name: "Mountain vs River",
    seed: Gardens.createMountainVsRiver(),
    mode: "2p-ns",
    createdAt: new Date().toISOString(),
  },
  {
    id: "default-siege",
    name: "Siege of the North",
    seed: Gardens.createSiegeOfTheNorth(),
    mode: "2p-ns",
    createdAt: new Date().toISOString(),
  },
  {
    id: "default-gauntlet",
    name: "The Gauntlet",
    seed: Gardens.createTheGauntlet(),
    mode: "2p-ns",
    createdAt: new Date().toISOString(),
  },

  // Strategic/Abstract Layouts
  {
    id: "default-pass",
    name: "Mountain Pass",
    seed: Strategic.createMountainPass(),
    mode: "2p-ns",
    createdAt: new Date().toISOString(),
  },
  {
    id: "default-dunes",
    name: "The Dunes",
    seed: Strategic.createTheDunes(),
    mode: "2p-ew",
    createdAt: new Date().toISOString(),
  },
  {
    id: "default-desert",
    name: "The Great Desert",
    seed: Strategic.createGreatDesert(),
    mode: "2p-ns",
    createdAt: new Date().toISOString(),
  },
  {
    id: "default-rockies",
    name: "The Rockies",
    seed: Strategic.createTheRockies(),
    mode: "2p-ns",
    createdAt: new Date().toISOString(),
  },
  {
    id: "default-crossfire",
    name: "Crossfire",
    seed: Strategic.createCrossfire(),
    mode: "2p-ns",
    createdAt: new Date().toISOString(),
  },
  {
    id: "default-cage",
    name: "The Cage",
    seed: Strategic.createTheCage(),
    mode: "2p-ns",
    createdAt: new Date().toISOString(),
  },
  {
    id: "default-arena",
    name: "The Arena",
    seed: Strategic.createTheArena(),
    mode: "2p-ns",
    createdAt: new Date().toISOString(),
  },
  {
    id: "default-crossroads",
    name: "Crossroads",
    seed: Strategic.createCrossroads(),
    mode: "2p-ns",
    createdAt: new Date().toISOString(),
  },
  {
    id: "default-target",
    name: "Target Practice",
    seed: Strategic.createTargetPractice(),
    mode: "2p-ns",
    createdAt: new Date().toISOString(),
  },
  {
    id: "default-wall",
    name: "The Wall",
    seed: Strategic.createTheWall(),
    mode: "2p-ns",
    createdAt: new Date().toISOString(),
  },
  {
    id: "default-fortress",
    name: "The Fortress",
    seed: Strategic.createTheFortress(),
    mode: "2p-ns",
    createdAt: new Date().toISOString(),
  },
  {
    id: "default-checkered",
    name: "Checkered Past",
    seed: Strategic.createCheckeredPast(),
    mode: "2p-ns",
    createdAt: new Date().toISOString(),
  },
  {
    id: "default-grid",
    name: "The Grid",
    seed: Strategic.createTheGrid(),
    mode: "2p-ns",
    createdAt: new Date().toISOString(),
  },
  {
    id: "default-corners",
    name: "Corner Conflicts",
    seed: Strategic.createCornerConflicts(),
    mode: "2p-ns",
    createdAt: new Date().toISOString(),
  },
  {
    id: "default-void",
    name: "The Void",
    seed: Strategic.createTheVoid(),
    mode: "2p-ns",
    createdAt: new Date().toISOString(),
  },
  {
    id: "default-maze",
    name: "The Maze",
    seed: Strategic.createTheMaze(),
    mode: "2p-ns",
    createdAt: new Date().toISOString(),
  },
  {
    id: "default-galaxy",
    name: "The Galaxy",
    seed: Strategic.createTheGalaxy(),
    mode: "2p-ns",
    createdAt: new Date().toISOString(),
  },
];
