export {
  DesertIcon,
  QueenIcon as BattleKnightIcon,
  KingIcon as CommanderIcon,
  BishopIcon as SniperIcon,
  RookIcon as TankIcon,
  KnightIcon as HorsemanIcon,
  PawnIcon as BotIcon,
  KingIcon,
  QueenIcon,
  BishopIcon,
  RookIcon,
  KnightIcon,
  PawnIcon,
} from "@/shared/components/atoms/UnitIcons";
